/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OurOilRouteImport } from './routes/our-oil'
import { Route as OurOilIndexRouteImport } from './routes/our-oil.index'
import { Route as OurOilSlugRouteImport } from './routes/our-oil.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OurOilRoute = OurOilRouteImport.update({
  id: '/our-oil',
  path: '/our-oil',
  getParentRoute: () => rootRouteImport,
} as any)
const OurOilIndexRoute = OurOilIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OurOilRoute,
} as any)
const OurOilSlugRoute = OurOilSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => OurOilRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/our-oil': typeof OurOilRouteWithChildren
  '/our-oil/$slug': typeof OurOilSlugRoute
  '/our-oil/': typeof OurOilIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/our-oil/$slug': typeof OurOilSlugRoute
  '/our-oil': typeof OurOilIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/our-oil': typeof OurOilRouteWithChildren
  '/our-oil/$slug': typeof OurOilSlugRoute
  '/our-oil/': typeof OurOilIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/our-oil' | '/our-oil/$slug' | '/our-oil/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/our-oil/$slug' | '/our-oil'
  id: '__root__' | '/' | '/our-oil' | '/our-oil/$slug' | '/our-oil/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OurOilRoute: typeof OurOilRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-oil': {
      id: '/our-oil'
      path: '/our-oil'
      fullPath: '/our-oil'
      preLoaderRoute: typeof OurOilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-oil/': {
      id: '/our-oil/'
      path: '/'
      fullPath: '/our-oil/'
      preLoaderRoute: typeof OurOilIndexRouteImport
      parentRoute: typeof OurOilRoute
    }
    '/our-oil/$slug': {
      id: '/our-oil/$slug'
      path: '/$slug'
      fullPath: '/our-oil/$slug'
      preLoaderRoute: typeof OurOilSlugRouteImport
      parentRoute: typeof OurOilRoute
    }
  }
}

interface OurOilRouteChildren {
  OurOilSlugRoute: typeof OurOilSlugRoute
  OurOilIndexRoute: typeof OurOilIndexRoute
}

const OurOilRouteChildren: OurOilRouteChildren = {
  OurOilSlugRoute: OurOilSlugRoute,
  OurOilIndexRoute: OurOilIndexRoute,
}

const OurOilRouteWithChildren =
  OurOilRoute._addFileChildren(OurOilRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OurOilRoute: OurOilRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
